# Generated by Django 2.1.7 on 2019-04-07 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_bugs_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugsupvote',
            old_name='upvoted_issue',
            new_name='upvoted_bug',
        ),
        migrations.AlterField(
            model_name='bugs',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
