# Generated by Django 2.1.7 on 2019-04-08 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_auto_20190407_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugsupvote',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
