# Generated by Django 2.1.7 on 2019-04-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_bugs_bug_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugs',
            old_name='bug_type',
            new_name='issue_type',
        ),
    ]
