# Generated by Django 2.1.7 on 2019-04-12 13:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0010_auto_20190411_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bugs',
            new_name='Issues',
        ),
    ]
