# Generated by Django 2.1.7 on 2019-04-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0012_auto_20190412_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Waiting', max_length=50),
        ),
    ]
