# Generated by Django 2.1.7 on 2019-04-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0013_auto_20190425_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('bugs.issues',),
        ),
    ]
