# Generated by Django 2.1.7 on 2019-04-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0014_ticketproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketProxy',
        ),
        migrations.CreateModel(
            name='Bugs',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('bugs.issues',),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('bugs.issues',),
        ),
    ]
